repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    files: \.bash
  - id: check-json
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: check-ast
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    # see https://github.com/gruntwork-io/pre-commit/releases
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.19
  hooks:
  - id: shellcheck
- repo: local
  hooks:
  - id: check-sh
    name: check bash scripts' formats
    entry: ./scripts/shfmt.bash
    language: script
