name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  plugin-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: semtag

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Cache tools
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Move semtag plugin to asdf plugins dir
        run: |
          mv semtag ${ASDF_DIR}/plugins/

      - name: Run semtag plugin tests
        run: |
          echo "Trying to list all versions of semtag"
          asdf list all semtag
          echo "Trying to install semtag 0.1.1 (the current version)"
          asdf install semtag 0.1.1
          semtag --version 2>&1 | grep '0.1.1'
